### ISSUE TITLE
trapperkeeper throwing exceptions on fresh PE 2016.2 installation on RHEL7.2

### ISSUE THREAD

**Issue by CalvinHartwell** [puppetlabs/trapperkeeper#245]
Hey,

Trapperkeeper is throwing exceptions on a fresh PE2016.2/RHEL7.2 installation. 

It has been deployed in a test environment as an all-in-one deployment through the web installer, here is the exception: 

```
Jul 15 17:30:04 ericcartman java: Exception in thread "main" java.lang.RuntimeException: Service ':FileSyncStorageService' not found
Jul 15 17:30:04 ericcartman java: at puppetlabs.trapperkeeper.internal$handle_prismatic_exception_BANG_.invoke(internal.clj:98)
Jul 15 17:30:04 ericcartman java: at puppetlabs.trapperkeeper.internal$instantiate$fn__13793.invoke(internal.clj:139)
Jul 15 17:30:04 ericcartman java: at puppetlabs.trapperkeeper.internal$instantiate.invoke(internal.clj:136)
Jul 15 17:30:04 ericcartman java: at puppetlabs.trapperkeeper.internal$eval14328$build_app_STAR___14337$fn__14338.invoke(internal.clj:542)
Jul 15 17:30:04 ericcartman java: at puppetlabs.trapperkeeper.internal$eval14328$build_app_STAR___14337.invoke(internal.clj:510)
Jul 15 17:30:04 ericcartman java: at puppetlabs.trapperkeeper.internal$eval14430$boot_services_STAR___14439$fn__14440$fn__14441.invoke(internal.clj:610)
Jul 15 17:30:04 ericcartman java: at puppetlabs.trapperkeeper.internal$eval14430$boot_services_STAR___14439$fn__14440.invoke(internal.clj:609)
Jul 15 17:30:04 ericcartman java: at puppetlabs.trapperkeeper.internal$eval14430$boot_services_STAR___14439.invoke(internal.clj:604)
Jul 15 17:30:04 ericcartman java: at puppetlabs.trapperkeeper.core$eval15252$boot_with_cli_data__15259$fn__15260.invoke(core.clj:130)
Jul 15 17:30:04 ericcartman java: at puppetlabs.trapperkeeper.core$eval15252$boot_with_cli_data__15259.invoke(core.clj:95)
Jul 15 17:30:04 ericcartman java: at puppetlabs.trapperkeeper.core$eval15281$run__15286$fn__15287.invoke(core.clj:151)
Jul 15 17:30:04 ericcartman java: at puppetlabs.trapperkeeper.core$eval15281$run__15286.invoke(core.clj:145)
Jul 15 17:30:04 ericcartman java: at puppetlabs.trapperkeeper.core$main.doInvoke(core.clj:173)
Jul 15 17:30:04 ericcartman java: at clojure.lang.RestFn.invoke(RestFn.java:457)
Jul 15 17:30:04 ericcartman java: at clojure.lang.Var.invoke(Var.java:394)
Jul 15 17:30:04 ericcartman java: at clojure.lang.AFn.applyToHelper(AFn.java:165)
Jul 15 17:30:04 ericcartman java: at clojure.lang.Var.applyTo(Var.java:700)
Jul 15 17:30:04 ericcartman java: at clojure.core$apply.invoke(core.clj:630)
Jul 15 17:30:04 ericcartman java: at puppetlabs.trapperkeeper.main$_main.doInvoke(main.clj:7)
Jul 15 17:30:04 ericcartman java: at clojure.lang.RestFn.invoke(RestFn.java:457)
Jul 15 17:30:04 ericcartman java: at clojure.lang.Var.invoke(Var.java:394)
Jul 15 17:30:04 ericcartman java: at clojure.lang.AFn.applyToHelper(AFn.java:165)
Jul 15 17:30:04 ericcartman java: at clojure.lang.Var.applyTo(Var.java:700)
Jul 15 17:30:04 ericcartman java: at clojure.core$apply.invoke(core.clj:630)
Jul 15 17:30:04 ericcartman java: at clojure.main$main_opt.invoke(main.clj:316)
Jul 15 17:30:04 ericcartman java: at clojure.main$main.doInvoke(main.clj:421)
Jul 15 17:30:04 ericcartman java: at clojure.lang.RestFn.invoke(RestFn.java:512)
Jul 15 17:30:04 ericcartman java: at clojure.lang.Var.invoke(Var.java:409)
Jul 15 17:30:04 ericcartman java: at clojure.lang.AFn.applyToHelper(AFn.java:178)
Jul 15 17:30:04 ericcartman java: at clojure.lang.Var.applyTo(Var.java:700)
Jul 15 17:30:04 ericcartman java: at clojure.main.main(main.java:37)

```

The hostname is ericcartman, the pe-java version is 1.8.0.91-2.bl4.pe.el7.x86_64. Not sure how to check the clojure version? 

Any idea what might be causing this? Every part of PE is fine but the pe-pupperserver service is constantly bombing out and restarting. 

Cheers,

- Calvin

**Comment by cprice404** [comment]
This is now captured in:

https://tickets.puppetlabs.com/browse/SERVER-1451
