### ISSUE TITLE
Cannot Initialize Service Depending on a Service Depending on Jetty 9 WebserverService 

### ISSUE THREAD

**Issue by timur87** [puppetlabs/trapperkeeper#259]
Hi, 

I have a service (service 1) depending on jetty9-service [1], I can initialize this service and it runs as expected. I have another service (service 2) depending on service 1. When I try to initialize service 2, I get the following error. I'm using clojure 1.9.0-alpha13 and tk 1.5.2. Any ideas about the problem? 

[1] puppetlabs.trapperkeeper.services.webserver.jetty9-service/jetty9-service
```
java.lang.RuntimeException: Service ':WebserverService' not found
	at puppetlabs.trapperkeeper.internal$handle_prismatic_exception_BANG_.invokeStatic(internal.clj:121)
	at puppetlabs.trapperkeeper.internal$handle_prismatic_exception_BANG_.invoke(internal.clj:111)
	at puppetlabs.trapperkeeper.internal$instantiate$fn__15473.invoke(internal.clj:162)
	at puppetlabs.trapperkeeper.internal$instantiate.invokeStatic(internal.clj:159)
	at puppetlabs.trapperkeeper.internal$instantiate.invoke(internal.clj:152)
	at puppetlabs.trapperkeeper.internal$eval16017$build_app_STAR___16026$fn__16027.invoke(internal.clj:569)
	at puppetlabs.trapperkeeper.internal$eval16017$build_app_STAR___16026.invoke(internal.clj:537)
	at puppetlabs.trapperkeeper.internal$eval16121$boot_services_STAR___16130$fn__16131$fn__16132.invoke(internal.clj:639)
	at puppetlabs.trapperkeeper.internal$eval16121$boot_services_STAR___16130$fn__16131.invoke(internal.clj:638)
	at puppetlabs.trapperkeeper.internal$eval16121$boot_services_STAR___16130.invoke(internal.clj:633)
	at puppetlabs.trapperkeeper.core$eval16976$boot_with_cli_data__16983$fn__16984.invoke(core.clj:130)
	at puppetlabs.trapperkeeper.core$eval16976$boot_with_cli_data__16983.invoke(core.clj:95)
	at puppetlabs.trapperkeeper.core$eval17005$run__17010$fn__17011.invoke(core.clj:151)
	at puppetlabs.trapperkeeper.core$eval17005$run__17010.invoke(core.clj:145)
	at puppetlabs.trapperkeeper.core$main.invokeStatic(core.clj:173)
	at puppetlabs.trapperkeeper.core$main.doInvoke(core.clj:159)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.core$apply.invokeStatic(core.clj:657)
	at clojure.core$apply.invoke(core.clj:652)
	at puppetlabs.trapperkeeper.main$_main.invokeStatic(main.clj:7)
	at puppetlabs.trapperkeeper.main$_main.doInvoke(main.clj:4)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at user$eval17057.invokeStatic(form-init5981974856700142042.clj:1)
	at user$eval17057.invoke(form-init5981974856700142042.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6977)
	at clojure.lang.Compiler.eval(Compiler.java:6967)
	at clojure.lang.Compiler.load(Compiler.java:7429)
	at clojure.lang.Compiler.loadFile(Compiler.java:7367)
	at clojure.main$load_script.invokeStatic(main.clj:277)
	at clojure.main$init_opt.invokeStatic(main.clj:279)
	at clojure.main$init_opt.invoke(main.clj:279)
	at clojure.main$initialize.invokeStatic(main.clj:310)
	at clojure.main$null_opt.invokeStatic(main.clj:344)
	at clojure.main$null_opt.invoke(main.clj:341)
	at clojure.main$main.invokeStatic(main.clj:423)
	at clojure.main$main.doInvoke(main.clj:386)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Exception in thread "main" java.lang.RuntimeException: Service ':WebserverService' not found, compiling:(/tmp/form-init5981974856700142042.clj:1:73)
	at clojure.lang.Compiler.load(Compiler.java:7441)
	at clojure.lang.Compiler.loadFile(Compiler.java:7367)
	at clojure.main$load_script.invokeStatic(main.clj:277)
	at clojure.main$init_opt.invokeStatic(main.clj:279)
	at clojure.main$init_opt.invoke(main.clj:279)
	at clojure.main$initialize.invokeStatic(main.clj:310)
	at clojure.main$null_opt.invokeStatic(main.clj:344)
	at clojure.main$null_opt.invoke(main.clj:341)
	at clojure.main$main.invokeStatic(main.clj:423)
	at clojure.main$main.doInvoke(main.clj:386)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: java.lang.RuntimeException: Service ':WebserverService' not found
	at puppetlabs.trapperkeeper.internal$handle_prismatic_exception_BANG_.invokeStatic(internal.clj:121)
	at puppetlabs.trapperkeeper.internal$handle_prismatic_exception_BANG_.invoke(internal.clj:111)
	at puppetlabs.trapperkeeper.internal$instantiate$fn__15473.invoke(internal.clj:162)
	at puppetlabs.trapperkeeper.internal$instantiate.invokeStatic(internal.clj:159)
	at puppetlabs.trapperkeeper.internal$instantiate.invoke(internal.clj:152)
	at puppetlabs.trapperkeeper.internal$eval16017$build_app_STAR___16026$fn__16027.invoke(internal.clj:569)
	at puppetlabs.trapperkeeper.internal$eval16017$build_app_STAR___16026.invoke(internal.clj:537)
	at puppetlabs.trapperkeeper.internal$eval16121$boot_services_STAR___16130$fn__16131$fn__16132.invoke(internal.clj:639)
	at puppetlabs.trapperkeeper.internal$eval16121$boot_services_STAR___16130$fn__16131.invoke(internal.clj:638)
	at puppetlabs.trapperkeeper.internal$eval16121$boot_services_STAR___16130.invoke(internal.clj:633)
	at puppetlabs.trapperkeeper.core$eval16976$boot_with_cli_data__16983$fn__16984.invoke(core.clj:130)
	at puppetlabs.trapperkeeper.core$eval16976$boot_with_cli_data__16983.invoke(core.clj:95)
	at puppetlabs.trapperkeeper.core$eval17005$run__17010$fn__17011.invoke(core.clj:151)
	at puppetlabs.trapperkeeper.core$eval17005$run__17010.invoke(core.clj:145)
	at puppetlabs.trapperkeeper.core$main.invokeStatic(core.clj:173)
	at puppetlabs.trapperkeeper.core$main.doInvoke(core.clj:159)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.core$apply.invokeStatic(core.clj:657)
	at clojure.core$apply.invoke(core.clj:652)
	at puppetlabs.trapperkeeper.main$_main.invokeStatic(main.clj:7)
	at puppetlabs.trapperkeeper.main$_main.doInvoke(main.clj:4)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at user$eval17057.invokeStatic(form-init5981974856700142042.clj:1)
	at user$eval17057.invoke(form-init5981974856700142042.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6977)
	at clojure.lang.Compiler.eval(Compiler.java:6967)
	at clojure.lang.Compiler.load(Compiler.java:7429)
```

**Comment by KevinCorcoran** [comment]
> When I try to initialize service 2, I get the following error.

How, exactly, are you trying to initialize service 2?

Note that, to use service 2, you'll need to include all 3 services in bootstrap.cfg:
```
puppetlabs.trapperkeeper.services.webserver.jetty9-service/jetty9-service
my.namespace/service-1
another.namespace/service-2
```

**Comment by timur87** [comment]
Okay thanks for the information, I was not aware of the fact that we need to include transitive service dependencies as well. 

Including the web service in bootstrap.cfg solved the issue.
