### ISSUE TITLE
Compiler exceptions are not visible

### ISSUE THREAD

**Issue by msprunck** [puppetlabs/trapperkeeper#264]
Compilation exceptions can be hidden

When I start trapperkeeper I get this assertion error:
```
clojure.lang.Compiler$CompilerException: java.lang.AssertionError: Assert failed: (keyword? kw), compiling:(/private/var/folders/64/dm10kp_d3flbv7h57w_lvh640000gp/T/form-init7417682376252201391.clj:1:125)
  at clojure.lang.Compiler.load(Compiler.java:7391)
  at clojure.lang.Compiler.loadFile(Compiler.java:7317)
  at clojure.main$load_script.invokeStatic(main.clj:275)
  at clojure.main$init_opt.invokeStatic(main.clj:277)
  at clojure.main$init_opt.invoke(main.clj:277)
  at clojure.main$initialize.invokeStatic(main.clj:308)
  at clojure.main$null_opt.invokeStatic(main.clj:342)
  at clojure.main$null_opt.invoke(main.clj:339)
  at clojure.main$main.invokeStatic(main.clj:421)
  at clojure.main$main.doInvoke(main.clj:384)
  at clojure.lang.RestFn.invoke(RestFn.java:421)
  at clojure.lang.Var.invoke(Var.java:383)
  at clojure.lang.AFn.applyToHelper(AFn.java:156)
  at clojure.lang.Var.applyTo(Var.java:700)
  at clojure.main.main(main.java:37)
Caused by: java.lang.AssertionError: Assert failed: (keyword? kw)
  at puppetlabs.kitchensink.core$without_ns.invokeStatic(core.clj:572)
  at puppetlabs.kitchensink.core$without_ns.invoke(core.clj:572)
  at puppetlabs.trapperkeeper.core$main.invokeStatic(core.clj:177)
  at puppetlabs.trapperkeeper.core$main.doInvoke(core.clj:160)
  at clojure.lang.RestFn.applyTo(RestFn.java:137)
  at clojure.core$apply.invokeStatic(core.clj:646)
  at clojure.core$apply.invoke(core.clj:641)
  at mania.core$_main.invokeStatic(core.clj:27)
  at mania.core$_main.doInvoke(core.clj:25)
  at clojure.lang.RestFn.invoke(RestFn.java:457)
  at clojure.lang.Var.invoke(Var.java:394)
  at user$eval16724.invokeStatic(form-init7417682376252201391.clj:1)
  at user$eval16724.invoke(form-init7417682376252201391.clj:1)
  at clojure.lang.Compiler.eval(Compiler.java:6927)
  at clojure.lang.Compiler.eval(Compiler.java:6917)
  at clojure.lang.Compiler.load(Compiler.java:7379)
  ... 14 common frames omitted
  ```

In the `main` function of [`core.clj`](https://github.com/puppetlabs/trapperkeeper/blob/29ca3010f13d614fc98c59e785134a91f98cb4ce/src/puppetlabs/trapperkeeper/core.clj#L175) all map passed to `ex-info` are expected to contain a `:type` keyword. A compilation exception is also an `ex-info` without this keyword.

```
(defn main
  "Launches the trapperkeeper framework. This function blocks until
  trapperkeeper is shut down. This may be called directly, but is also called by
  `puppetlabs.trapperkeeper.core/-main` if you use `puppetlabs.trapperkeeper.core`
  as the `:main` namespace in your leinengen project."
  [& args]
  {:pre [((some-fn sequential? nil?) args)
         (every? string? args)]}
  (let [quit (fn [status msg stream]
               (binding [*out* stream] (println msg) (flush))
               (System/exit status))]
    (try+
      (-> (or args '())
          (internal/parse-cli-args!)
          (run))
      (catch map? m
        (case (without-ns (:type m))
          :cli-error (quit 1 (:message m) *err*)
          :cli-help (quit 0 (:message m) *out*)
          (throw+)))
      (finally
        (log/debug (i18n/trs "Finished TK main lifecycle, shutting down Clojure agent threads."))
        (shutdown-agents)))))
```

When a map passed to an `ex-info` does not contain the `:type` keyword, the [`without-ns`](https://github.com/puppetlabs/clj-kitchensink/blob/master/src/puppetlabs/kitchensink/core.clj#L613) function throws an assertion error.

**Comment by camlow325** [comment]
Thanks, @msprunck.  I went ahead and filed a ticket for this into the Puppet JIRA tracker, [TK-439](https://tickets.puppetlabs.com/browse/TK-439), and put up a [PR](https://github.com/puppetlabs/trapperkeeper/pull/265) with a fix for handling the `:type` key in the map that you pointed out.

Closing this issue out in favor of the other ticket and PR.

**Comment by kisspuppet** [comment]
有坑~~
